name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build_ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: mishas/setup-bazelisk-action@v1
      - name: bazel cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //...
      - run: bazel test //...
  build_windows_latest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mishas/setup-bazelisk-action@v1
      - name: bazel cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazelisk build //...
      - run: bazelisk test //...
