name: Bzlmod Archive

on:
  release:
    types: [published]

jobs:
  bzlmod-archive:
    uses: bazelboost/registry/.github/workflows/bzlmod-archive.yml@main
    secrets: inherit
    permissions:
      contents: write
